# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 11:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flags', '0002_auto_20170927_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flag',
            name='assignee',
        ),
        migrations.AddField(
            model_name='flag',
            name='handler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flag_handler', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flag',
            name='object_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flag_object_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flagcomment',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
