# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 16:09
from __future__ import unicode_literals

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.UUIDField(default=account.models.ResetPassword.transaction_default)),
                ('token', models.CharField(default=account.models.ResetPassword.token_default, max_length=68)),
                ('expire_date', models.DateTimeField(db_index=True, default=account.models.ResetPassword.expire_date_default)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
