# Generated by Django 2.0.1 on 2018-01-24 12:41
# Modified so field is renamed and Altered in one migration

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_resetpassword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confirmmail',
            old_name='nonce',
            new_name='token',
        ),
        migrations.AlterField(
            model_name='confirmmail',
            name='token',
            field=models.CharField(default=account.models.token_default, max_length=68),
        ),
    ]
