# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-07 15:42
from __future__ import unicode_literals

import areas.base.posts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.IntegerField(default=areas.base.posts.models.Post.generate_nonce)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('text', models.TextField()),
                ('stack_count', models.IntegerField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areas_information_posts_post', to=settings.AUTH_USER_MODEL)),
                ('stack_assigned', models.ManyToManyField(db_index=True, related_name='areas_information_posts_post_assigned', to=settings.AUTH_USER_MODEL)),
                ('stack_done', models.ManyToManyField(db_index=True, related_name='areas_information_posts_post_done', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
