# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-10 22:41
from __future__ import unicode_literals

import areas.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(db_index=True, max_length=30)),
                ('nonce', models.IntegerField(default=areas.models.Post.generate_nonce)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('text', models.TextField()),
                ('stack_outstanding', models.IntegerField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('stack_assigned', models.ManyToManyField(db_index=True, related_name='post_assigned', to=settings.AUTH_USER_MODEL)),
                ('stack_done', models.ManyToManyField(db_index=True, related_name='post_done', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reputation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(db_index=True, max_length=30)),
                ('reputation', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areas.Post'),
        ),
        migrations.CreateModel(
            name='funPost',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('areas.post',),
        ),
        migrations.CreateModel(
            name='informationPost',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('areas.post',),
        ),
        migrations.AlterUniqueTogether(
            name='reputation',
            unique_together=set([('area', 'user')]),
        ),
    ]
