# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 17:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='unread',
            field=models.ManyToManyField(related_name='comment_unread', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='subscriber',
            field=models.ManyToManyField(related_name='post_subscriber', to=settings.AUTH_USER_MODEL),
        ),
    ]
