# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-18 18:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_auto_20170324_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='unread',
            field=models.ManyToManyField(blank=True, related_name='comment_unread', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='subscriber',
            field=models.ManyToManyField(blank=True, related_name='post_subscriber', to=settings.AUTH_USER_MODEL),
        ),
    ]
