# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-01 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0003_auto_20170518_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='anonym',
            field=models.BooleanField(default=False),
        ),
    ]
