# Generated by Django 2.0.1 on 2018-05-12 18:11

import areas.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0006_auto_20180403_0316'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('image', models.ImageField(upload_to=areas.models.image_path)),
                ('comment', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'ordering': ['num'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=areas.models.image_path),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=areas.models.image_path),
        ),
        migrations.AddField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='areas.Post'),
        ),
        migrations.AlterUniqueTogether(
            name='postimage',
            unique_together={('post', 'num')},
        ),
    ]
