# Generated by Django 2.1.5 on 2019-03-24 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0008_areas_in_db'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='active',
        ),
    ]
