# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 17:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reason', models.IntegerField(choices=[(1, 'Rude'), (2, 'Spam'), (3, 'Offtopic (Wrong area)'), (None, 'Other (Please explain)')], null=True)),
                ('comment', models.TextField(blank=True)),
                ('auto', models.BooleanField(default=False)),
                ('ban_all', models.BooleanField(default=False)),
                ('ban_post', models.BooleanField(default=False)),
                ('ban_comment', models.BooleanField(default=False)),
                ('ban_flag', models.BooleanField(default=False)),
                ('expiry', models.DateTimeField(blank=True, null=True)),
                ('unbanned', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Warn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reason', models.IntegerField(choices=[(1, 'Rude'), (2, 'Spam'), (3, 'Offtopic (Wrong area)'), (None, 'Other (Please explain)')], null=True)),
                ('comment', models.TextField(blank=True)),
                ('auto', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
