# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ban',
            name='reason',
            field=models.IntegerField(blank=True, choices=[(1, 'Rude'), (2, 'Spam'), (3, 'Offtopic (Wrong area)'), (None, 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='warn',
            name='reason',
            field=models.IntegerField(blank=True, choices=[(1, 'Rude'), (2, 'Spam'), (3, 'Offtopic (Wrong area)'), (None, 'Other')], null=True),
        ),
    ]
