# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-02 12:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas_information_rep', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reputation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='areas_information_rep_reputation', to=settings.AUTH_USER_MODEL),
        ),
    ]
